- name: Docker cleanup
  hosts: all
  become: true
  tasks:
    - name: Docker remove unused images
      command: docker image prune -a -f
    - name: Docker prune everything
      command: docker system prune -a -f
