- name: Docker cleanup
  hosts: all
  become: true
  tasks:
    - name: Docker prune everything
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true